### ISSUE TITLE
backticks crashes with tox version >= 3.21.0

### ISSUE THREAD

**Issue by axelfauvel** [jayvdb/tox-backticks#16]
Here is the stacktrace :

tox changed `_ArgvlistReader.getargvlist` signature on 3.21.0.

It went from

```python
def getargvlist(cls, reader, value, replace=True):
```

to

```python
def getargvlist(cls, reader, value, replace=True, name=None):
```

name is defined to None but is asserted later in the function as you can see in the stacktrace below.

```
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/commands/run/sequential.py", line 22, in run_sequential
    runtestenv(venv, config)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/session/commands/run/sequential.py", line 73, in runtestenv
    config.pluginmanager.hook.tox_runtest_pre(venv=venv)
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/project/.tox/.tox/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox_backticks.py", line 64, in tox_runtest_pre
    _run_backtick(reader, venv, variable)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox_backticks.py", line 26, in _run_backtick
    argvlist = _ArgvlistReader.getargvlist(reader, cmdstr, replace=True)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1967, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace, name=name))
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1993, in processcommand
    new_word = reader._replace(word, name=name)
  File "/project/.tox/.tox/lib/python3.8/site-packages/tox/config/__init__.py", line 1785, in _replace
    assert name
AssertionError
```

After taking a look to tox code, it seems that name refers to tox sub-sub-section (don't know the exact terminology). In tox-backticks scope, it is `setenv`.

I will provide PR to fix this problem.

**Comment by jayvdb** [comment]
Thanks for reporting this.
I acutally caused this bug: https://github.com/tox-dev/tox/pull/1720 ;-)

**Comment by axelfauvel** [comment]
yes you did ^^

**Comment by axelfauvel** [comment]
Hi @jayvdb, when did you plan to release this contribution ?

**Comment by axelfauvel** [comment]
Hello @jayvdb, any news on releasing ?

**Comment by jayvdb** [comment]
Released now. Apologies for the delay.
